[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions/dist"

[[redirects]]
  from = "/trpc/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200